### ISSUE TITLE
[PE-D] "contacted" example in User Guide shows incorrect usage

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W13-4/tp#214]
"contacted" command example usage in User Guide does not include "dt/" prefix.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: AAlghrairy/ped#17

**Comment by sheimoria** [comment]
Duplicate of #223

**Comment by sheimoria** [comment]
Duplicate of #223
